using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace Gestion_WF.Articulos
{
    public partial class ArticulosEditar : Form
    {

        MyEntityModel.ApplicationDbContextSql dbContext = new MyEntityModel.ApplicationDbContextSql();
        public ArticulosEditar()
        {
            InitializeComponent();
        }

        public ArticulosEditar(int id)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Articulos.Where(w => w.ArticuloID == id).Load();
            // This line of code is generated by Data Source Configuration Wizard
            dataLayoutControl1.DataSource = dbContext.Articulos.Local.ToBindingList();

            dbContext.TipoArticulos.Load();
            TipoArticuloIDLookUpEdit.Properties.DataSource = dbContext.TipoArticulos.Local.ToBindingList();
            TipoArticuloIDLookUpEdit.Properties.DisplayMember = "Nombre";
            TipoArticuloIDLookUpEdit.Properties.ValueMember = "TipoArticuloID";

            dbContext.Ivas.Load();
            IvaIDTextEdit.Properties.DataSource = dbContext.Ivas.Local.ToBindingList();
            IvaIDTextEdit.Properties.DisplayMember = "Nombre";
            IvaIDTextEdit.Properties.ValueMember = "IvaID";

            dbContext.Recargos.Load();
            RecargoIDTextEdit.Properties.DataSource = dbContext.Recargos.Local.ToBindingList();
            RecargoIDTextEdit.Properties.DisplayMember = "Nombre";
            RecargoIDTextEdit.Properties.ValueMember = "RecargoID";
        }

        private void simpleButtonGrabar_Click(object sender, EventArgs e)
        {
            dbContext.SaveChanges();
            MyEntityModel.FuncionesInterbase FU = new MyEntityModel.FuncionesInterbase();
            FU.conectar();
            this.Close();
        }

   
    }
}
